import { z } from "zod";

export const modelConfigSchema = z.object({
  species: z.string().min(1),
  modelId: z.string().min(1),
  biovars: z.array(z.number().int().min(1).max(19)).min(2),
  projectionExtent: z.tuple([
    z.number().min(-180).max(180),
    z.number().min(-180).max(180),
    z.number().min(-90).max(90),
    z.number().min(-90).max(90),
  ]).refine(([xmin, xmax, ymin, ymax]) => xmin < xmax && ymin < ymax, {
    message: "Invalid extent: xmin must be < xmax and ymin must be < ymax",
  }),
  backgroundN: z.number().int().min(500).max(100000).default(10000),
  cvFolds: z.number().int().min(0).max(10).default(3),
  cvStrategy: z.enum(["random", "spatial_blocks"]).default("random"),
  cvBlockSizeKm: z.number().min(1).max(500).optional(),
  threshold: z.number().min(0.05).max(0.95).default(0.5),
  includeQuadratic: z.boolean().default(true),
  useElevation: z.boolean().default(false),
  elevationDemtype: z.string().default("COP90"),
  opentopoApiKey: z.string().optional(),
  useSoil: z.boolean().default(false),
  soilVars: z.array(z.string()).default(["sand", "clay", "phh2o"]),
  soilDepths: z.array(z.string()).default(["0-5cm", "30-60cm"]),
  useUv: z.boolean().default(false),
  uvVars: z.array(z.string()).default(["UVB1", "UVB2"]),
  useVegetation: z.boolean().default(false),
  vegYear: z.number().int().optional(),
  vegProducts: z.array(z.string()).default(["ndvi_annual_mean"]),
  useLulc: z.boolean().default(false),
  lulcYear: z.number().int().default(2020),
  useHfp: z.boolean().default(false),
  hfpYear: z.number().int().default(2020),
  useBioclimSeason: z.boolean().default(false),
  useDrought: z.boolean().default(false),
  futureProjection: z.boolean().default(false),
  futureWorldclimDir: z.string().optional(),
  futureLabel: z.string().default("Future climate"),
  vifReduction: z.boolean().default(false),
  vifThreshold: z.number().min(1).max(20).default(10),
  climateMatching: z.boolean().default(false),
  climateMatchingMethod: z.enum(["mahalanobis", "standardised", "euclidean"]).default("mahalanobis"),
  thinByCell: z.boolean().default(true),
  mergeSmallSources: z.boolean().default(true),
  minSourceRecords: z.number().int().min(1).max(100).default(15),
  biasMethod: z.enum(["uniform", "target_group", "thickened"]).default("uniform"),
  thickeningDistanceKm: z.number().min(1).max(100).default(10),
  paReplicates: z.number().int().min(1).max(10).default(1),
  maxnetFeatures: z.enum(["l", "lq", "lqp", "lqh", "lqpht"]).default("lqp"),
  maxnetRegmult: z.number().min(0.1).max(10).default(1.0),
  aggregationFactor: z.number().int().min(1).max(8).default(1),
  nCores: z.number().int().min(1).max(64).default(1),
  seed: z.number().int().default(42),
  occurrenceFile: z.string().min(1),
  worldclimDir: z.string().default("Worldclim"),
  worldclimRes: z.number().default(10),
  source: z.enum(["worldclim", "chelsa"]).default("worldclim"),
  chelsaExtras: z.array(z.string()).default([]),
  cleanedFilePath: z.string().min(1).optional(),
  pipelineRunId: z.string().optional(),
});

export type ModelConfig = z.infer<typeof modelConfigSchema>;

export const modelRunSchema = z.object({
  id: z.string(),
  species: z.string(),
  modelId: z.string(),
  status: z.enum(["running", "completed", "failed", "queued"]),
  startedAt: z.string(),
  completedAt: z.string().nullable(),
  error: z.string().nullable(),
  metrics: z.object({
    aucMean: z.number().nullable(),
    aucSd: z.number().nullable(),
    tssMean: z.number().nullable(),
    tssSd: z.number().nullable(),
    presenceRecords: z.number().nullable(),
    backgroundPoints: z.number().nullable(),
    elapsedSeconds: z.number().nullable(),
    highSuitabilityAreaKm2: z.number().nullable(),
  }).nullable(),
  outputFiles: z.record(z.string()).nullable(),
  progressLog: z.array(z.string()).default([]),
});

export type ModelRun = z.infer<typeof modelRunSchema>;

export const occurrenceUploadSchema = z.object({
  filename: z.string(),
  speciesFilter: z.string().optional(),
  maxCoordinateUncertainty: z.number().optional(),
});
