## Biomod2 modelling wrapper ---------------------------------------------------
## Centralizes all calls to the biomod2 package. Registers via model_registry
## only when options(sdm.enable_biomod2 = TRUE) and biomod2 is installed.
## See BIOMOD2_ADAPTER_NOTES.md for gating strategy details.

run_biomod2 <- function(occ_df, pred_stack, models = NULL,
                        background_n = 1000, cv_folds = 3,
                        species_name = NULL, seed = 42,
                        output_dir = tempdir(), log_fun = NULL, progress_fun = NULL) {
  if (is.null(models)) {
    models <- config$biomod2_default
  }

  sp_name <- if (!is.null(species_name)) {
    species_name
  } else if (!is.null(occ_df$species)) {
    occ_df$species[1]
  } else {
    "species"
  }

  log_message(log_fun, "Running biomod2 with models: ", paste(models, collapse = ", "))

  set.seed(seed)
  pa_points <- terra::spatSample(pred_stack,
    size = background_n,
    method = "random", na.rm = TRUE,
    as.points = TRUE, xy = TRUE
  )

  if (is.null(pa_points) || terra::nrow(pa_points) == 0) {
    stop("Failed to generate pseudo-absence points for biomod2", call. = FALSE)
  }

  pa_df <- as.data.frame(pa_points)
  pa_xy <- data.frame(longitude = pa_df$x, latitude = pa_df$y)
  pres_xy <- data.frame(longitude = occ_df$longitude, latitude = occ_df$latitude)

  all_xy <- rbind(pres_xy, pa_xy)
  all_response <- c(rep(1, nrow(occ_df)), rep(0, nrow(pa_xy)))

  biomod_data <- biomod2::BIOMOD_FormatingData(
    resp.var = all_response,
    expl.var = pred_stack,
    resp.name = sp_name,
    resp.xy = all_xy,
    na.rm = TRUE
  )

  modeling_id <- paste0("sdm_", safe_slug(sp_name), "_", format(Sys.time(), "%Y%m%d_%H%M%S"))

  bm_opts <- biomod2::bm_ModelingOptions(bm.format = biomod_data, strategy = "default")

  # Use compat layer to validate/filter arguments against installed biomod2 signature
  user_args <- list(
    bm.format = biomod_data,
    models = models,
    modeling.id = modeling_id,
    CV.strategy = "kfold",
    CV.nb.rep = 1,
    CV.perc = (cv_folds - 1) / cv_folds,
    OPT.strategy = "default",
    OPT.user = bm_opts,
    output.dir = file.path(output_dir, modeling_id)
  )
  if (check_cancelled(log_fun)) {
    return(invisible(NULL))
  }
  biomod_mod <- do.call(biomod2::BIOMOD_Modeling, user_args)

  evaluations <- biomod2::get_evaluations(biomod_mod)
  var_importance <- biomod2::get_variables_importance(biomod_mod)

  eval_df <- data.frame(
    algorithm = rownames(evaluations),
    auc = as.numeric(evaluations[, "AUC", "Testing", "AllData"]),
    tss = as.numeric(evaluations[, "TSS", "Testing", "AllData"]),
    stringsAsFactors = FALSE
  )
  rownames(eval_df) <- NULL

  auc_vals <- eval_df$auc
  tss_vals <- eval_df$tss

  varimp_df <- data.frame(
    variable = rownames(var_importance),
    importance = as.numeric(var_importance[, 1]),
    stringsAsFactors = FALSE
  )
  rownames(varimp_df) <- NULL

  list(
    model = biomod_mod,
    formula = NULL,
    coefficients = eval_df,
    occurrence_used = occ_df,
    background_xy = pa_xy,
    cv = list(
      k = cv_folds,
      strategy = "kfold",
      auc_mean = mean(auc_vals, na.rm = TRUE),
      auc_sd = sd(auc_vals, na.rm = TRUE),
      tss_mean = mean(tss_vals, na.rm = TRUE),
      tss_sd = sd(tss_vals, na.rm = TRUE),
      per_algorithm = eval_df
    ),
    covariates = names(pred_stack),
    variable_importance = varimp_df,
    binary_metrics = NULL,
    model_id = "biomod2",
    modeling_id = modeling_id
  )
}

predict_biomod2_suitability <- function(fit, env_project_scaled, output_tif,
                                        n_cores = 1, log_fun = NULL) {
  proj_name <- paste0("proj_", fit$modeling_id)

  proj <- biomod2::BIOMOD_Projection(
    bm.mod = fit$model,
    new.env = env_project_scaled,
    proj.name = proj_name,
    output.dir = file.path(tempdir(), fit$modeling_id),
    build.clamping.mask = TRUE
  )

  proj_files <- list.files(file.path(tempdir(), fit$modeling_id, proj_name),
    pattern = "\\.tif$", full.names = TRUE
  )
  proj_files <- proj_files[!grepl("clamping", proj_files)]

  if (length(proj_files) == 0) {
    stop("No projection files generated by biomod2", call. = FALSE)
  }

  final_file <- proj_files[length(proj_files)]

  if (!is.null(output_tif)) {
    terra::writeRaster(terra::rast(final_file), output_tif,
      overwrite = TRUE,
      wopt = list(gdal = c("COMPRESS=DEFLATE", "PREDICTOR=2", "ZLEVEL=6", "TILED=YES", "NAflag=-9999"))
    )
  }

  terra::rast(final_file)
}
