version = "2"
replication_factor = 1

data_dir = "/var/lib/garage"
metadata_dir = "/var/lib/garage/meta"
rpc_bind_addr = "0.0.0.0:3902"
rpc_secret = "5a343800bc4a1bfad79d31bc9dc7185287e28bd20bf6c34c31769c935c731fce"
bootstrap_token = "sdm-bootstrap-token"

[s3_api]
api_bind_addr = "0.0.0.0:3900"
web_bind_addr = "0.0.0.0:3901"
s3_region = "garage"

[s3_api.credentials]
access_key_id = "sdm"
secret_access_key = "sdm_garage_secret"

[replication]
strategy = "none"